# Generated by Django 4.1.5 on 2023-01-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muksamo', '0002_rename_subject_question_bung_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Bung_List',
        ),
    ]
